### ISSUE TITLE
Message on user enter the group

### ISSUE THREAD

**Issue by Pandry** [Scienza/scienziati_bot#20]
The bot should send a message when a user enters the group, saying welcome and inviting the user to subscribe to some lists

**Comment by RagazzaSmarties** [comment]
Hi

**Comment by RagazzaSmarties** [comment]
Comunque pensavo ad una cosa tipo:
"Benvenuto/a 😊
Presentati se ti va
Hai interessi particolari e vuoi essere avvisato quando se ne parla nel gruppo? Entra in @scienzati_bot iscriviti e registrati nelle liste che ti interessano
Buona permanenza dallo staff di @scienza😁"

**Comment by Pandry** [comment]
Ok, non male
Solo invece di "entra" direi qualcosa di simile a "utilizza il nostro bot @scienziati_bot per iscriverti e ..."

**Comment by RagazzaSmarties** [comment]
"Benvenuto/a 😊
Presentati se ti va
Hai interessi particolari e vuoi essere avvisato quando se ne parla nel gruppo? Utilizza il nostro bot @scienzati_bot per iscriverti e registrarti nelle liste che ti interessano
Buona permanenza dallo staff di @Scienza😁"


Meglio?

**Comment by Pandry** [comment]
In fase di aggiornamento

**Comment by Pandry** [comment]
Aggiornato a:
Presentati se ti va
Hai interessi particolari e vuoi essere avvisato quando se ne parla nel gruppo? Utilizza il nostro bot @scienzati_bot per iscriverti e registrarti nelle liste che ti interessano.
Al fine di non "intasare" la chat con messaggi da parte mia, sei inviatato ad avviarmi in privato.
In caso di dubbi, il comando /help o /aiuto sarà a tua disposizione.
Buona permanenza dallo staff di @Scienza😁
